# Generated by Django 4.2.10 on 2024-02-17 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_good_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ('name',)},
        ),
        migrations.AlterIndexTogether(
            name='good',
            index_together={('id', 'slug')},
        ),
    ]
