# Generated by Django 4.2.10 on 2024-02-17 20:47

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_good_options_alter_good_index_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='good',
            name='stock',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='good',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
