# Generated by Django 4.2.10 on 2024-02-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_good_created_good_stock_good_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='category',
        ),
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ManyToManyField(related_name='goods', to='shop.category'),
        ),
    ]
