# Generated by Django 4.2.10 on 2024-02-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_good_category_good_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='tag',
        ),
        migrations.AddField(
            model_name='good',
            name='tag',
            field=models.ManyToManyField(to='shop.tag'),
        ),
    ]
