# Generated by Django 4.2.10 on 2024-02-18 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_good_tag_good_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_fat', models.CharField(max_length=20)),
                ('saturated_fat', models.CharField(max_length=20)),
                ('cholesterol', models.CharField(max_length=20)),
                ('total_carbohydrate', models.CharField(max_length=20)),
                ('protein', models.CharField(max_length=20)),
                ('total_sugars', models.CharField(max_length=20)),
                ('sodium', models.CharField(max_length=20)),
                ('calcium', models.CharField(max_length=20)),
                ('potassium', models.CharField(max_length=20)),
                ('good', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='protein_info', to='shop.good')),
            ],
            options={
                'verbose_name': 'Protein',
                'verbose_name_plural': 'Proteins',
            },
        ),
    ]
