# Generated by Django 4.2.10 on 2024-02-18 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_protein'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='category',
        ),
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='shop.category'),
        ),
    ]
