# Generated by Django 4.2.10 on 2024-02-18 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_good_category_good_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='shop.category'),
        ),
    ]
