# Generated by Django 4.2.10 on 2024-02-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_good_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='good',
            name='type_good',
        ),
    ]
