# Generated by Django 4.2.10 on 2024-02-18 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_good_tag_remove_good_type_good'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='good',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Protein',
        ),
    ]
